name: suit
description: A library of platform adaptation scheme based on the ViewPort(vw, vh) and Relative Position(rw, rh).
version: 1.1.0
homepage: https://github.com/ggdream/suit

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
